# <<BEGIN-copyright>>
# <<END-copyright>>

SHELL = /bin/ksh

sourceDir = ../Src

.PHONY: default check clean realclean

default: ptwX.h

ptwX.h:
	cp $(sourceDir)/ptwX.h .

check:

clean:
	rm -f *.h

realclean: clean
