# <<BEGIN-copyright>>
# <<END-copyright>>

SHELL = /bin/ksh

.PHONY: default check clean realclean

default:

check:
	python groupTestAll1.py
	python integrationXY.py
	python integrationWithWeight_x.py
	python integrationWithWeight_sqrt_x.py

clean:

realclean: clean
