# <<BEGIN-copyright>>
# Copyright 2021, Lawrence Livermore National Security, LLC.
# See the top-level COPYRIGHT file for details.
# 
# SPDX-License-Identifier: BSD-3-Clause
# <<END-copyright>>

SHELL = /bin/sh

PYTHON = python

.PHONY: default check clean realclean

default:

check:
	$(PYTHON) add.py
	$(PYTHON) mul.py

clean:

realclean: clean
