# <<BEGIN-copyright>>
# <<END-copyright>>

SHELL = /bin/ksh

.PHONY: default check clean realclean

default:

check:
	python exponentialIntegralTest.py

checke:
	$(MAKE) check CHECKOPTIONS=-e

clean:

realclean: clean
