# <<BEGIN-copyright>>
# Copyright 2022, Lawrence Livermore National Security, LLC.
# See the top-level COPYRIGHT file for details.
# 
# SPDX-License-Identifier: BSD-3-Clause
# <<END-copyright>>


.PHONY: clean realclean

default:
	cd Src; $(MAKE)

all: default

clean:
	cd Src; $(MAKE) clean

realclean:
	cd Src; $(MAKE) realclean
