# <<BEGIN-copyright>>
# <<END-copyright>>

SHELL = /bin/ksh

.PHONY: default headers clean realclean

default: headers

headers:
	cp $(NFUPDATING_PATH)/include/*.h .

clean:
	rm -f *.h

realclean: clean
