# <<BEGIN-copyright>>
# Copyright 2022, Lawrence Livermore National Security, LLC.
# See the top-level COPYRIGHT file for details.
# 
# SPDX-License-Identifier: BSD-3-Clause
# <<END-copyright>>

SHELL = /bin/sh

sourceDir = ../Src

.PHONY: headers clean realclean

headers:
	cp $(sourceDir)/nf_specialFunctions.h .

clean:
	rm -f *.h

realclean: clean
