# <<BEGIN-copyright>>
# Copyright 2022, Lawrence Livermore National Security, LLC.
# See the top-level COPYRIGHT file for details.
# 
# SPDX-License-Identifier: BSD-3-Clause
# <<END-copyright>>

SHELL = /bin/sh

PYTHON = python

TARGETS = thicken

.PHONY: default check clean realclean

default:

check: default
	$(PYTHON) thicken.py

clean:

realclean: clean
