name: FUDGE

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.12", "3.13"]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display environment
        run: python -c "import sys, platform; print(platform.system()); print(sys.version)"

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel numpy h5py

      - name: Install FUDGE
        run: python -m pip install git+https://github.com/LLNL/fudge.git@ci_dev

